/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Sqt2K4f9ITY
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import PlusIcon from "../icons/Plus"

export function AddButton() {
  return (
    <Button
      //variant="ghost"
      size="icon"
      className="rounded-full h-8 w-8 bg-primary text-primary-foreground hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
    >
      <PlusIcon className="h-5 w-5" />
    </Button>
  )
}
