/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/nQFXmbR1KLC
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Searchbar from "./searchbar"
import ChatPreview from "./chat-preview"
import ChatHeader from "./chat-header"
import NewMessage from "./new-message"
import ChatMessage from "./chat-message"

export function ChatLayout() {
  return (
    <div className="grid h-screen w-full grid-cols-[300px_1fr] bg-background">
      <div className="flex flex-col border-r bg-background sticky top-0 left-0 max-h-screen">
        <Searchbar />
        <div className="flex-1 overflow-auto self-start">
          <div className="grid gap-2 p-4">
            <ChatPreview />
          </div>
        </div>
      </div>
      <div className="flex flex-col max-h-screen">
        <ChatHeader />
        <div className="flex-1 overflow-auto p-6">
          <div className="grid gap-4">
            <ChatMessage isUser={false} />
            <ChatMessage isUser/>
            <ChatMessage isUser/>
            <ChatMessage isUser/>
            <ChatMessage isUser/>
            <ChatMessage isUser/>
            <ChatMessage isUser/>
            <ChatMessage isUser/>
          </div>
        </div>
        <NewMessage />
      </div>
    </div>
  )
}








