/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/HRMHPT2hJS6
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";
import { AddButton } from "./add-button";

export function NewChatDialog() {
  return (
    <Dialog>
      <DialogTrigger>
        <AddButton />
      </DialogTrigger>
      <DialogContent className="sm:max-w-[600px]">
        <DialogHeader>
          <DialogTitle>New Chat</DialogTitle>
          <div />
        </DialogHeader>
        <div className="relative flex-1">
          <div className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
          <Input
            type="search"
            placeholder="Search users..."
            className="w-full rounded-lg bg-background pl-8"
          />
        </div>
        <div className="grid gap-4 max-h-[400px] overflow-auto">
          <div className="grid grid-cols-[auto_1fr] items-center gap-4">
            <Avatar>
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>JD</AvatarFallback>
            </Avatar>
            <div className="grid gap-1">
              <div className="font-medium">John Doe</div>
            </div>
          </div>
          <div className="grid grid-cols-[auto_1fr] items-center gap-4">
            <Avatar>
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>JS</AvatarFallback>
            </Avatar>
            <div className="grid gap-1">
              <div className="font-medium">Jane Smith</div>
            </div>
          </div>
          <div className="grid grid-cols-[auto_1fr] items-center gap-4">
            <Avatar>
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>BJ</AvatarFallback>
            </Avatar>
            <div className="grid gap-1">
              <div className="font-medium">Bob Johnson</div>
            </div>
          </div>
          <div className="grid grid-cols-[auto_1fr] items-center gap-4">
            <Avatar>
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>SL</AvatarFallback>
            </Avatar>
            <div className="grid gap-1">
              <div className="font-medium">Sarah Lee</div>
            </div>
          </div>
          <div className="grid grid-cols-[auto_1fr] items-center gap-4">
            <Avatar>
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>MC</AvatarFallback>
            </Avatar>
            <div className="grid gap-1">
              <div className="font-medium">Michael Chen</div>
            </div>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
